"""Baseline migration

Revision ID: c58c8e46d84c
Revises: 
Create Date: 2026-01-11 20:53:38.362525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c58c8e46d84c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_ibfk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_ibfk_4'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
